apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pods-get-list-watch
  namespace: prometheus
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]