apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pods-get-list-watch
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:prometheus
roleRef:
  kind: Role
  name: pods-get-list-watch
  apiGroup: rbac.authorization.k8s.io